import '~/assets/libs/js/jquery-3.2.1.min.js'
import '~/assets/libs/js/bootstrap.js'
import '~/assets/libs/js/jquery.counterup.min.js'
import '~/assets/libs/js/jquery.waypoints.min.js'
import '~/assets/libs/js/scrollreveal.min.js'
import '~/assets/libs/slick/slick.min.js'
