const {
  NODE_ENV,
  PAYPAL_CLIENT,
  PAYPAL_CLIENT_SANDBOX,
  PAYPAL_SECRET,
  PAYPAL_SECRET_SANDBOX,
  PAYPAL_AMOUNT
} = process.env

const PAYPAL_BASE_API = NODE_ENV ? 'https://api.paypal.com' : 'https://api.sandbox.paypal.com'

const CLIENT = NODE_ENV ? PAYPAL_CLIENT || '' : PAYPAL_CLIENT_SANDBOX || ''
const SECRET = NODE_ENV ? PAYPAL_SECRET || '' : PAYPAL_SECRET_SANDBOX || ''
const STANDARD_PAY_AMOUNT = NODE_ENV ? PAYPAL_AMOUNT || '0.01' : '0.01'

module.exports = { PAYPAL_BASE_API, CLIENT, SECRET, STANDARD_PAY_AMOUNT }
